name: ChannelEngineMerchantApiClient
targets:
  ChannelEngineMerchantApiClient:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [ChannelEngineMerchantApiClient]
    info:
      path: ./Info.plist
      version: 2.9.3
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
